# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "rails" do |o|
    o.vm.box = "centos/7"
    o.vm.hostname = "admin"
    o.vm.network :private_network, ip: "192.168.100.10"

    # itamae provision
    o.vm.provision :itamae do |itamae|
      itamae.sudo = true
      itamae.shell = '/bin/sh'
      itamae.recipes = '../roles/node.rb'
      itamae.json = '../nodes/node.json'
    end
  end
end
